name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          sudo apt-get update -yqq
          sudo apt-get install -yqq --no-install-recommends build-essential clang libelf-dev zlib1g-dev pkg-config libbpf-dev protobuf-compiler
      
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy
      
      - name: Print version info
        run: rustc --version && cargo --version
      
      - name: Run tests
        run: cargo test --workspace --verbose
      
      - name: Check formatting
        run: cargo fmt --all -- --check
      
      - name: Run clippy
        run: cargo clippy -- -D warnings
      
      - name: Build
        run: cargo build
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lime-rtw
          path: target/*/lime-rtw
          retention-days: 1 
